services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      # nginx exposes port 80 internally
      - '${SERVER_PORT}:80'
    volumes:
      # https://hub.docker.com/_/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  # php:
  # mysql:
  # composer:
  # artisan:
  # npm:
