services:
  server:
    image: 'nginx:stable-alpine'
    ports:
      # nginx exposes port 80 internally
      - '${SERVER_PORT}:80'
    volumes:
      # https://hub.docker.com/_/nginx - :ro = read only volume
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated # 'delegated' improves performance by not instantly syncing changes from host to container
    ports:
      - '3333:9000' # expose php-fpm port for nginx to connect to - NOT NEEDED and should change port in nginx.conf to 9000, but left here for learning purposes

  mysql:
    image: 'mysql:8.0'
    env_file:
      - ./env/mysql.env

  composer:

  # artisan:
  # npm:
