services:
  # Compose creates a shared network and adds all services by default
  mongodb:
    image: mongo:latest
    # The MongoDB container stores its data internally in the /data/db directory by default
    volumes:
      - data:/data/db
    env_file:
      - ./.env.backend
    # Compose creates a shared network and adds all services by default
    # networks:
    # - app-net

  db:
    build: ./db
    depends_on:
      - mongodb
    env_file:
      - ./.env.backend

  backend:
    build:
      # Explicit example with dockerfile in root and context (build dir) separate:
      context: ./backend
      # Dockerfile path relative to the build context
      dockerfile: ../Dockerfile-backend
      # args:
      #   NODE_ENV: production
    volumes:
      # Named volume
      - logs:/app/logs
      # Anonymous volume
      - /app/node_modules
      # Relative paths allowed for bind-mounts in docker-compose
      - ./backend:/app
    environment:
      - PORT=4444
      # alt format PORT: 4444
    env_file:
      - ./.env.backend
    ports:
      - '4444:4444'
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - '4173:80'

volumes:
  data: # Needed for named volumes eg services.mongodb.volumes - Anon and bind-mounts not needed here
  logs:
