services:
  # Compose creates a shared network and adds all services by default
  mongodb:
    image: mongo:latest
    # The MongoDB container stores its data internally in the /data/db directory by default
    volumes:
      - data:/data/db
    env_file:
      - ./.env.backend
    # Compose creates a shared network and adds all services by default
    # networks:
    # - app-net

  db:
    build: ./db
    depends_on:
      - mongodb
    env_file:
      - ./.env.backend

  backend:
    build:
      # Explicit example with dockerfile in root and context (build dir) separate:
      context: ./backend
      # Dockerfile path relative to the build context
      dockerfile: ../Dockerfile-backend
      # args:
      #   NODE_ENV: production
    volumes:
      # Named volume for persisting logs inside "container" outside container lifecycle
      - logs:/app/logs
      # Anonymous volume
      - /app/node_modules
      # Relative paths allowed for bind-mounts in docker-compose
      - ./backend:/app
    environment:
      # Example of passing env var from .env file to container
      - PORT=${BACKEND_PORT}
      # alt format PORT: 4444
    env_file:
      - ./.env.backend
    ports:
      - '${BACKEND_PORT}:4444'
    depends_on:
      - db

  frontend-2: # Standard naming for container is ${foldername}_${servicename}_${incrementor} - eg compose-basic_frontend-2_1
    container_name: frontend-1 # Alternative way to name containers
    build:
      context: ./frontend
      args:
        - FRONTEND_PORT=${FRONTEND_PORT}
        - BACKEND_PORT=${BACKEND_PORT}

    depends_on:
      - backend
    ports:
      - '${FRONTEND_PORT}:80'
    # Below is an example of the compose equivalent of `docker run -it`
    stdin_open: true # Equivalent to docker run -i
    tty: true # Equivalent to docker run -t

  frontend:
    build:
      context: ./frontend
      args:
        - FRONTEND_PORT=5555
        - BACKEND_PORT=${BACKEND_PORT}

    depends_on:
      - backend
    ports:
      - '5555:80'
    # Below is an example of the compose equivalent of `docker run -it`
    stdin_open: true # Equivalent to docker run -i
    tty: true # Equivalent to docker run -t

volumes:
  data: # Needed for named volumes eg services.mongodb.volumes - Anon and bind-mounts not needed here
  logs:
