services:
  # Compose creates a shared network and adds all services by default
  mongodb:
    image: mongo:latest
    volumes:
      - data:/data/db
    env_file:
      - ./db/.env
    # Compose creates a shared network and adds all services by default
    networks:
    # - app-net
  backend:
    volumes:
      - ./backend/logs:/logs
    environment:
      - PORT=4444
      # alt format PORT: 4444

  volumes:
    data: # Needed for named volumes eg services.mongodb.volumes - Anon and bind-mounts not needed here
